(function () {
  'use strict';

  /** Reglas ordenadas de más específica a más general */
  const RULES = [
    {
      test: /espacio vectorial|vectores en el espacio/i,
      definition: 'Un espacio vectorial V es un conjunto donde sumar vectores y multiplicar por escalares está definido. En física, posición, velocidad y fuerza son vectores en ℝ³ expresados en una base {î, ĵ, k̂}.',
      keyPoints: ['Vector = magnitud + dirección + sentido', 'Base: conjunto de vectores linealmente independientes que generan V', 'Componentes dependen de la base elegida'],
      formulas: ['v = v_x î + v_y ĵ + v_z k̂', '|v| = √(v_x² + v_y² + v_z²)'],
      simGuide: 'Observa cómo cambian las componentes al mover los vectores. La suma a+b cierra el paralelogramo.',
      example: { problem: '<p>v = (3, 4, 0). Calcula |v| y las componentes en una base rotada 90° en el plano xy.</p>', solution: '<p>|v| = <strong>5</strong>. Tras rotar: v′ ≈ (−4, 3, 0).</p>' },
    },
    {
      test: /espacio dual|covector/i,
      definition: 'El espacio dual V* contiene los covectores: aplicaciones lineales α: V → ℝ. Físicamente, un covector mide la proyección de un vector sobre una dirección sin ser él mismo un vector.',
      keyPoints: ['Covector = funcional lineal, notación α(v)', 'Dual de la base: base {αⁱ} con αⁱ(e_j) = δⁱⱼ', 'Producto escalar puede verse como acción de un covector'],
      formulas: ['α(v) ∈ ℝ', 'dim V* = dim V'],
      simGuide: 'El producto escalar a·b mide cuánto de b hay en la dirección de a: interpretación covectorial.',
      example: { problem: '<p>¿Es f(v) = 2v_x + v_y un covector válido?</p>', solution: '<p>Sí: es <strong>lineal</strong> en v (f(av₁+bv₂) = af(v₁)+bf(v₂)).</p>' },
    },
    {
      test: /levi-civita|producto cruz|índices/i,
      definition: 'El producto cruz a×b es un vector perpendicular al plano de a y b, con magnitud |a||b|sin θ. El símbolo εᵢⱼₖ (Levi-Civita) compacta la notación de índices en ℝ³.',
      keyPoints: ['a×b = −b×a (anti conmutativo)', 'ε₁₂₃ = +1; dos índices iguales → 0', '(a×b)_i = εᵢⱼₖ aⱼ bₖ'],
      formulas: ['|a×b| = |a||b| sin θ', 'a·(b×c) = det(a,b,c)'],
      simGuide: 'Ajusta a y b: el vector verde a×b es perpendicular y su longitud es el área del paralelogramo.',
      example: { problem: '<p>î × ĵ = ?</p>', solution: '<p><strong>k̂</strong> (regla de la mano derecha).</p>' },
    },
    {
      test: /tensor/i,
      definition: 'Un tensor lineal T: V → V transforma vectores en vectores. En física modela deformaciones, momentos de inercia y conductividades: sus componentes dependen de la base pero la transformación es covariante/contravariante.',
      keyPoints: ['T(v) es vector si T es lineal', 'Matriz de T en base {e_i}: T_ij = e_i · T(e_j)', 'Tensores de rango 2 tienen 9 componentes en 3D'],
      formulas: ['v′ = T v', 'Tr(T) = Σ T_ii'],
      simGuide: 'La figura muestra cómo una transformación lineal deforma y rota un triángulo: det(T) mide cambio de área/volumen.',
      example: { problem: '<p>T = diag(2, 1). ¿Qué pasa al vector (1,1)?</p>', solution: '<p>T(1,1) = <strong>(2, 1)</strong>.</p>' },
    },
    {
      test: /matrices.*rotacion|rotaciones y traslacion/i,
      definition: 'Las matrices ortogonales R (RᵀR = I, det R = 1) representan rotaciones rígidas. Las traslaciones no son lineales en 3D pero sí en coordenadas homogéneas 4×4.',
      keyPoints: ['Rotación 2D: R(θ) rota ángulo θ', 'Composición de rotaciones = producto de matrices', 'Traslación + rotación → grupo de Galilei en mecánica'],
      formulas: ['R(θ) = [[cos θ, −sin θ],[sin θ, cos θ]]', 'x′ = R x + t'],
      simGuide: 'Gira el ángulo θ y observa que la figura rota sin deformarse: |v| se conserva.',
      example: { problem: '<p>Rota (1,0) por 90°.</p>', solution: '<p>Resultado: <strong>(0, 1)</strong>.</p>' },
    },
    {
      test: /curvatura|torsión|curvas en el espacio/i,
      definition: 'Una curva parametrizada r(s) tiene curvatura κ = |dr/ds × d²r/ds²|/|dr/ds|³ que mide qué tan rápido cambia la dirección tangente. La torsión τ mide la salida del plano osculador.',
      keyPoints: ['κ grande → curva muy curvada', 'Circunferencia: κ = 1/R constante', 'τ = 0 → curva plana'],
      formulas: ['κ = |v × a| / |v|³', 'v = ds/dt'],
      simGuide: 'La trayectoria elíptica muestra cómo κ varía: máxima en los vértices, mínima donde el radio osculador es mayor.',
      example: { problem: '<p>Circunferencia R = 2 m. ¿κ?</p>', solution: '<p>κ = <strong>0.5 m⁻¹</strong>.</p>' },
    },
    {
      test: /movimiento rectilíneo|mru|mrua|cinemática/i,
      definition: 'La cinemática describe el movimiento sin causas. MRU: v constante. MRUA: a constante. Movimiento rotatorio: |v| constante pero dirección cambia → aceleración centrípeta.',
      keyPoints: ['x(t) en MRU es línea recta en gráfico x-t', 'MRUA: parábola en x-t', 'MCU: a_c = v²/R hacia el centro'],
      formulas: ['x = x₀ + vt', 'x = x₀ + v₀t + ½at²', 'a_c = ω²R'],
      simGuide: 'El gráfico superior muestra x(t); el inferior la posición en la recta o círculo. Reproduce y compara v y a.',
      example: { problem: '<p>MRUA: a = 2 m/s², v₀ = 0, t = 3 s. ¿x?</p>', solution: '<p>x = ½·2·9 = <strong>9 m</strong>.</p>' },
    },
    {
      test: /coordenadas|cartesianas|polares|cilíndricas|esféricas/i,
      definition: 'Las coordenadas curvilíneas adaptan la geometría: cartesianas (x,y,z), polares (r,θ), cilíndricas (ρ,φ,z) y esféricas (r,θ,φ). El jacobiano J convierte elementos de volumen dV.',
      keyPoints: ['Misma posición, distintas coordenadas', 'Polares: x = r cos θ, y = r sin θ', 'dV_esférico = r² sin θ dr dθ dφ'],
      formulas: ['ds² = dx² + dy² + dz²', '∇² en esféricas incluye términos 1/r²'],
      simGuide: 'Visualiza cómo un punto fijo cambia de componentes al pasar de cartesianas a polares: la posición es la misma, las etiquetas no.',
      example: { problem: '<p>(r, θ) = (5, π/2). ¿Cartesianas?</p>', solution: '<p>(x, y) ≈ <strong>(0, 5)</strong>.</p>' },
    },
    {
      test: /galilei|marco inercial|referencia inercial/i,
      definition: 'Un marco inercial es aquel donde una partícula libre de fuerzas reales se mueve con velocidad constante. El grupo de Galilei une traslaciones, rotaciones y boosts v → v + V entre marcos inerciales.',
      keyPoints: ['Primera ley define marco inercial', 'Leyes de Newton válidas solo en marcos inerciales', 'Transformación galileana: t′ = t, x′ = x − Vt'],
      formulas: ['x′ = x − Vt', 'a′ = a (aceleración invariante)'],
      simGuide: 'Observa dos observadores: en el marco del suelo y en un tren inercial. La aceleración es la misma; la velocidad cambia por V.',
      example: { problem: '<p>Tren a 20 m/s. Pelota lanzada a 5 m/s adelante en el tren. ¿v en suelo?</p>', solution: '<p>v = <strong>25 m/s</strong>.</p>' },
    },
    {
      test: /fuerza y masa|segunda ley/i,
      definition: 'La segunda ley de Newton establece ΣF⃗ = m a⃗: la aceleración es proporcional a la fuerza neta e inversamente proporcional a la masa. Masa mide inercia (resistencia a cambiar velocidad).',
      keyPoints: ['Fuerza = interacción entre cuerpos', 'Masa inercial m en F = ma', 'Diagrama de cuerpo libre: aislar fuerzas sobre el cuerpo'],
      formulas: ['ΣF = ma', 'Peso P = mg'],
      simGuide: 'Aplica fuerza horizontal a un bloque: mayor F → mayor a; mayor m → menor a para la misma F.',
      example: { problem: '<p>F = 20 N, m = 5 kg, sin roce. ¿a?</p>', solution: '<p>a = <strong>4 m/s²</strong>.</p>' },
    },
    {
      test: /acción y reacción|equilibrio|tensión|normal/i,
      definition: 'Tercera ley: F₁₂ = −F₂₁ (acción-reacción en pares distintos). Equilibrio: ΣF = 0 implica a = 0. Tensión y normal son fuerzas de contacto que restringen movimiento.',
      keyPoints: ['Acción y reacción actúan en cuerpos diferentes', 'Equilibrio estático: ΣF = 0 y Στ = 0', 'Normal ⊥ superficie; tensión a lo largo de cuerda'],
      formulas: ['F₁₂ = −F₂₁', 'ΣF = 0 (equilibrio)'],
      simGuide: 'Identifica pares acción-reacción en el diagrama. En equilibrio, las flechas de fuerza se cancelan.',
      example: { problem: '<p>Libro 2 kg en mesa. ¿Normal?</p>', solution: '<p>N = mg = <strong>19.6 N</strong> hacia arriba.</p>' },
    },
    {
      test: /momento lineal|momento angular|impulso|torque/i,
      definition: 'Momento lineal p⃗ = m v⃗ se conserva si ΣF⃗_ext = 0. Momento angular L⃗ = r⃗ × p⃗ se conserva si Στ⃗_ext = 0. Impulso J = ∫F dt = Δp.',
      keyPoints: ['Conservación de p en choques sin fuerzas externas', 'L = r × p para partícula', 'Torque τ = r × F = dL/dt'],
      formulas: ['p = mv', 'L = r × p', 'J = Δp'],
      simGuide: 'Sin fuerzas externas, el centro de masa mantiene velocidad constante. Observa p total antes y después.',
      example: { problem: '<p>2 kg a 3 m/s choca y se une a 1 kg en reposo (inelástico). ¿v final?</p>', solution: '<p>v = 6/3 = <strong>2 m/s</strong>.</p>' },
    },
    {
      test: /trabajo|energía cinética|potencia/i,
      definition: 'Trabajo W = ∫F·dx. Teorema trabajo-energía: W_net = ΔK. Potencia P = dW/dt = F·v. Energía cinética K = ½mv².',
      keyPoints: ['W > 0 si F tiene componente en dirección del desplazamiento', 'Fuerza ⊥ desplazamiento no realiza trabajo', 'K escala con v²'],
      formulas: ['W = ∫F·dx', 'K = ½mv²', 'P = F·v'],
      simGuide: 'La barra de energía muestra K creciendo cuando la fuerza acelera la partícula en su dirección de movimiento.',
      example: { problem: '<p>F = 10 N, d = 4 m, dirección paralela. ¿W?</p>', solution: '<p>W = <strong>40 J</strong>.</p>' },
    },
    {
      test: /conservativ|energía potencial|gradiente|equipotencial/i,
      definition: 'Fuerza conservativa: F⃗ = −∇U con U potencial. El trabajo entre dos puntos no depende de la trayectoria. Superficies equipotenciales U = const son ⊥ a F⃗.',
      keyPoints: ['∇×F = 0 ⟺ F conservativa (simply connected)', 'W = −ΔU', 'Gravitatoria: U = mgh; elástica: U = ½kx²'],
      formulas: ['F = −∇U', 'E = K + U', 'W = −ΔU'],
      simGuide: 'Las líneas de gradiente apuntan hacia donde U disminuye más rápido. Mueve la partícula: W = −ΔU.',
      example: { problem: '<p>m = 1 kg, cae 5 m. ¿ΔU_grav?</p>', solution: '<p>ΔU = −mgh = <strong>−49 J</strong> (referencia abajo).</p>' },
    },
    {
      test: /energía mecánica|fricción|disipación/i,
      definition: 'E_mec = K + U se conserva solo sin fuerzas no conservativas (roce). El roce convierte E_mec en calor: W_roce = −f_k d < 0.',
      keyPoints: ['Con roce: ΔE_mec = W_roce', 'Rendimiento η = W_útil / Q_absorbido', 'Estacionario: entrada de energía = disipación'],
      formulas: ['ΔE_mec = W_no_cons', 'f_k = μ_k N'],
      simGuide: 'Con amortiguamiento β > 0, la amplitud decrece: energía mecánica se disipa. Compara β = 0 vs β > 0.',
      example: { problem: '<p>μ = 0.2, N = 50 N, d = 10 m. ¿W_roce?</p>', solution: '<p>W = −0.2·50·10 = <strong>−100 J</strong>.</p>' },
    },
    {
      test: /centro de masa|muchas partículas|reducido/i,
      definition: 'Centro de masa R⃗_cm = Σ m_i r⃗_i / M. Se mueve como si toda la masa estuviera ahí bajo ΣF_ext. Coordenada reducida μ = m₁m₂/(m₁+m₂) simplifica el problema de dos cuerpos.',
      keyPoints: ['CM acelera con F_ext/M', 'Movimiento interno no afecta CM', 'μ reduce dos cuerpos a uno en fuerza central'],
      formulas: ['R_cm = Σm_i r_i / M', 'μ = m₁m₂/(m₁+m₂)'],
      simGuide: 'Dos masas orbitan: el CM permanece fijo (o con v constante). Observa cómo m₁ y m₂ se mueven simétricamente respecto al CM.',
      example: { problem: '<p>m₁ = 2 kg en x=0, m₂ = 4 kg en x=6. ¿x_cm?</p>', solution: '<p>x_cm = (0+24)/6 = <strong>4 m</strong>.</p>' },
    },
    {
      test: /lagrange|euler-lagrange|coordenadas generalizadas/i,
      definition: 'L = T − V es el lagrangiano. Con coordenadas generalizadas q_i, las ecuaciones de Euler-Lagrange d/dt(∂L/∂q̇_i) − ∂L/∂q_i = 0 dan el movimiento sin fuerzas de ligadura explícitas.',
      keyPoints: ['q_i pueden ser ángulos, distancias, etc.', 'L elegido en marco inercial', 'Simetrías → cantidades conservadas (Noether)'],
      formulas: ['L = T − V', 'd/dt(∂L/∂q̇) − ∂L/∂q = 0'],
      simGuide: 'El péndulo: L = ½ml²θ̇² + mgl cos θ. Reproduce la oscilación: es la solución de Euler-Lagrange.',
      example: { problem: '<p>Péndulo simple: ¿ecuación para θ?</p>', solution: '<p>θ̈ + (g/l) sin θ = <strong>0</strong>.</p>' },
    },
    {
      test: /oscilador.*no-amortiguado|oscilador.*amortiguado|armónico unidimensional(?!.*forzado)/i,
      definition: 'Oscilador armónico: F = −kx → ẍ + ω₀²x = 0 con ω₀ = √(k/m). Con amortiguamiento β: ẍ + 2βẋ + ω₀²x = 0 (sub/sobre/crítico según β vs ω₀).',
      keyPoints: ['Solución libre: x = A cos(ωt + φ)', 'β < ω₀: oscilaciones amortiguadas', 'β = ω₀: amortiguamiento crítico (retorno más rápido sin oscilar)'],
      formulas: ['ẍ + ω₀²x = 0', 'ω₀ = √(k/m)', 'x = Ae^(−βt)cos(ω_d t)'],
      simGuide: 'Cambia β: subamortiguado oscila decayendo; crítico vuelve al equilibrio sin pasar; sobreamortiguado regresa lentamente.',
      example: { problem: '<p>k = 16 N/m, m = 1 kg. ¿ω₀?</p>', solution: '<p>ω₀ = <strong>4 rad/s</strong>, T = π/2 s.</p>' },
    },
    {
      test: /forzado|green|impulso|resonancia/i,
      definition: 'Forzamiento F₀ cos Ωt añade término inhomogéneo. En régimen estacionario la amplitud depende de Ω; en resonancia (Ω ≈ ω₀, β pequeño) la amplitud es máxima. Green function da respuesta a impulso.',
      keyPoints: ['Amplitud estacionaria A(Ω) con pico cerca de ω₀', 'Desfase pasa por π/2 en resonancia (β pequeño)', 'Función de Green: respuesta a δ(t)'],
      formulas: ['ẍ + 2βẋ + ω₀²x = F₀ cos Ωt', 'A(Ω) ∝ 1/|ω₀² − Ω² + i2βΩ|'],
      simGuide: 'Ajusta Ω cerca de ω₀: la amplitud crece (resonancia). F₀ controla la magnitud de la respuesta forzada.',
      example: { problem: '<p>β → 0, Ω = ω₀. ¿Amplitud?</p>', solution: '<p>Diverge idealmente → <strong>resonancia</strong> (en realidad limitada por β o no linealidad).</p>' },
    },
    {
      test: /acoplados|modos normales/i,
      definition: 'Osciladores acoplados tienen modos normales: patrones donde todas las masas oscilan a la misma frecuencia ω. Descomposición en modos diagonaliza el sistema acoplado.',
      keyPoints: ['Modo simétrico y antisimétrico en 2 masas', 'Frecuencias normales ω₁, ω₂', 'Cualquier movimiento = superposición de modos'],
      formulas: ['x_i = Σ A_i cos(ω_α t + φ_α)', 'Det(K − ω²M) = 0'],
      simGuide: 'Dos masas acopladas: modo simétrico (mueven juntas) y antisimétrico (opuestas). Observa la superposición en la gráfica.',
      example: { problem: '<p>Dos masas iguales k igual. ¿Modos?</p>', solution: '<p>Simétrico ω₁ = √(k/m); antisimétrico ω₂ = √(3k/m).</p>' },
    },
    {
      test: /dos cuerpos|masa reducida|baricentro|fuerza central/i,
      definition: 'Problema de dos cuerpos: separar movimiento del CM (MRU si no hay F_ext) y movimiento relativo bajo fuerza central F(r). Masa reducida μ = m₁m₂/(m₁+m₂) satisface μ r̈ = F(r).',
      keyPoints: ['CM: M R_cm = p_total', 'Relativo: solo depende de r = |r₁ − r₂|', 'Momento angular L = μ r² θ̇ conservado'],
      formulas: ['μ = m₁m₂/(m₁+m₂)', 'μ r̈ = F(r)'],
      simGuide: 'Dos cuerpos orbitan el baricentro: distancias inversamente proporcionales a las masas. μ gobierna la órbita relativa.',
      example: { problem: '<p>Tierra-Sol aproximado: ¿quién orbita el CM?</p>', solution: '<p>Ambos; CM casi en el <strong>Sol</strong> (M_Sol ≫ M_Tierra).</p>' },
    },
    {
      test: /kepler|elíptica|parabólica|hiperbólica/i,
      definition: 'Ley de Kepler para 1/r²: órbitas son cónicas (elipse, parábola, hipérbola). Elipse: E < 0; excentricidad 0 ≤ e < 1. r = p/(1 + e cos θ) con p = L²/(μGM).',
      keyPoints: ['Primera ley: elipse con foco en M', 'Segunda: áreas iguales en tiempos iguales', 'Tercera: T² ∝ a³'],
      formulas: ['r = a(1−e²)/(1+e cos θ)', 'E = −GMm/(2a)'],
      simGuide: 'Ajusta excentricidad e: e=0 → círculo; e→1 → elipse alargada; e≥1 → trayectorias abiertas.',
      example: { problem: '<p>e = 0. ¿Tipo de órbita?</p>', solution: '<p><strong>Circular</strong>.</p>' },
    },
    {
      test: /momento angular orbital|ley de áreas|excentricidad|energía orbital/i,
      definition: 'L = μ r² θ̇ = const → ley de áreas: dA/dt = L/(2μ). Energía E y L determinan e y a. Perihelio/aphelio: v máxima/mínima.',
      keyPoints: ['L conservado ⟹ plano orbital fijo', 'dA/dt constante (segunda ley de Kepler)', 'E < 0 liga la órbita'],
      formulas: ['dA/dt = L/(2μ)', 'e = √(1 + 2EL²/(μ(GMm)²))'],
      simGuide: 'El radio vector barre áreas iguales en tiempos iguales: más rápido cerca del foco (perihelio).',
      example: { problem: '<p>¿Dónde v es máxima en elipse?</p>', solution: '<p>En el <strong>perihelio</strong> (r mínimo).</p>' },
    },
    {
      test: /dispersión|rutherford|sección eficaz|blanco fijo/i,
      definition: 'Dispersión: partícula incidente deflectada por potencial central. Parámetro de impacto b y ángulo de dispersión θ relacionados. Rutherford: σ(θ) para Coulomb. Sección eficaz σ = área efectiva del blanco.',
      keyPoints: ['b grande → θ pequeño (grancampo lejano)', 'Rutherford predijo retroceso de α en núcleo', 'σ tiene unidades de área'],
      formulas: ['b = f(θ, energía, potencial)', 'σ = 2πb db'],
      simGuide: 'Partículas con distinto b salen con distinto θ. Rutherford: gran deflexión implica b pequeño (cerca del núcleo).',
      example: { problem: '<p>¿Qué midió Rutherford en 1911?</p>', solution: '<p>Ángulos grandes de dispersión → <strong>núcleo</strong> compacto y cargado.</p>' },
    },
    {
      test: /choque|colisión|restitución|inelástico|elástico/i,
      definition: 'Choques: conservación de p siempre; K solo en elásticos (e=1). Coeficiente de restitución e = |v_rel,después|/|v_rel,antes|. Centro de masa: marco donde p_total = 0 simplifica análisis.',
      keyPoints: ['1D elástico: fórmulas closed-form v₁′, v₂′', 'Inelástico perfecto: v₁′ = v₂′', 'Lab vs CM: transformación galileana'],
      formulas: ['p_total = const', 'e = (v₂−v₁)/(u₁−u₂)'],
      simGuide: 'Reproduce el choque: elástico conserva K; inelástico las masas se pegan con v común. Observa v₁′ y v₂′.',
      example: { problem: '<p>Elástico 1D: m₁ = m₂, u₂ = 0, u₁ = v. ¿Intercambio?</p>', solution: '<p>v₁′ = 0, v₂′ = <strong>v</strong> (intercambio de velocidades).</p>' },
    },
    {
      test: /rotatorios|centrífuga|coriolis|base rotante/i,
      definition: 'En marco rotante con Ω: aparecen fuerzas ficticias F_cf = −m Ω×(Ω×r) (centrífuga) y F_Cor = −2m Ω×v′. Permiten escribir Newton en el marco que rota con el cuerpo.',
      keyPoints: ['Centrífuga radial hacia afuera en frame rotante', 'Coriolis desvía movimiento hacia la derecha (Ω hacia arriba, NH)', 'v′ es velocidad medida en el marco rotante'],
      formulas: ['F_cf = mω²r (eje ⊥)', 'F_Cor = −2m Ω × v′'],
      simGuide: 'En plataforma rotante: objeto en reposo en el marco lab parece sentir centrifuga hacia afuera en el marco rotante.',
      example: { problem: '<p>ω = 2 rad/s, r = 1 m. ¿|a_cf|?</p>', solution: '<p>|a_cf| = ω²r = <strong>4 m/s²</strong>.</p>' },
    },
    {
      test: /equivalencia|elevador/i,
      definition: 'Principio de equivalencia (Einstein): no hay experimento local que distinga campo gravitacional uniforme g y aceleración del marco a = g. Base de la relatividad general.',
      keyPoints: ['Elevador acelerado ↑: peso aparente m(g+a)', 'Libre caída: aparente ingravidez', 'Límite local, no global'],
      formulas: ['g_eff = g − a_marco'],
      simGuide: 'Compara elevador en reposo vs acelerando: la balanza lee distinto peso aparente.',
      example: { problem: '<p>Elevador acelera ↑ 3 m/s². m = 70 kg. ¿Lectura báscula?</p>', solution: '<p>N = m(g+a) ≈ 70·12.8 = <strong>896 N</strong>.</p>' },
    },
    {
      test: /punto fijo|euler|so3|rotaciones finitas/i,
      definition: 'Rotación finita 3D: elemento de SO(3). Ángulos de Euler (φ, θ, ψ) parametrizan orientación. Con punto fijo: ω⃗ instantáneo pasa por el eje fijo.',
      keyPoints: ['Composición de rotaciones no conmuta en 3D', 'Matriz R ∈ SO(3): RᵀR = I', 'ω⃗ instantáneo cambia dirección en precesión'],
      formulas: ['R = R_z(ψ)R_y(θ)R_z(φ)', 'v = ω × r'],
      simGuide: 'Rotación 3D de un cuerpo rígido: observa cómo un eje fijo y ω instantáneo determinan el movimiento.',
      example: { problem: '<p>¿Cuántos parámetros independientes tiene R en 3D?</p>', solution: '<p><strong>3</strong> (ej. ángulos de Euler).</p>' },
    },
    {
      test: /sin un punto fijo|chasde|rodadura|traslación.*rotación/i,
      definition: 'Movimiento general de cuerpo rígido = traslación del CM + rotación alrededor del CM. Rodadura sin deslizar: v_cm = ωR. Teorema de Chasles: todo desplazamiento = traslación + rotación.',
      keyPoints: ['K_total = K_cm + K_rot', 'Rodadura: punto contacto instantáneamente en reposo', 'Deslizamiento: roce de deslizamiento disipa energía'],
      formulas: ['v = ω × r', 'v_cm = ωR (rodadura pura)'],
      simGuide: 'Rueda que rueda: CM se traslada mientras gira. Punto de contacto tiene v = 0 respecto al suelo.',
      example: { problem: '<p>R = 0.3 m, ω = 10 rad/s rodadura. ¿v_cm?</p>', solution: '<p>v = ωR = <strong>3 m/s</strong>.</p>' },
    },
    {
      test: /tensor de inercia|steiner|ejes principales|diagonaliz/i,
      definition: 'Tensor de inercia I_ij = Σ m_k (δ_ij r² − r_i r_j). Ejes principales diagonalizan I. Teorema de Steiner: I = I_cm + Md² para eje paralelo.',
      keyPoints: ['I diagonal → torque τ = I α componente a componente', 'Simetría del cuerpo simplifica I', 'Elipsoide de inercia visualiza I'],
      formulas: ['τ = I α', 'I = I_cm + Md²', 'I_barra extremo = ML²/3'],
      simGuide: 'Rotación respecto a distintos ejes: I mayor → misma τ produce menor α. Steiner desplaza el eje.',
      example: { problem: '<p>Barra M, L, eje en extremo. ¿I?</p>', solution: '<p>I = <strong>ML²/3</strong>.</p>' },
    },
    {
      test: /poisson|ecuaciones.*euler.*movimiento/i,
      definition: 'Ecuaciones de Euler: τ = I ω̇ + ω × (I ω) en marco corporal. Ecuación de Poisson: dR/dt = R [ω]× relaciona orientación y velocidad angular.',
      keyPoints: ['ω × (Iω) ≠ 0 si I no es esférico → precesión', 'Top simétrico: nutación y precesión', 'Poisson integra orientación en el tiempo'],
      formulas: ['τ = I ω̇ + ω × Iω', 'L = I ω'],
      simGuide: 'Precesión de un top: L cambia dirección por τ_ext; observa el cono de precesión.',
      example: { problem: '<p>I esférico. ¿Simplifica Euler?</p>', solution: '<p>ω × Iω = 0 → <strong>τ = I ω̇</strong> (como rotación escalar).</p>' },
    },
    {
      test: /plano complejo|modulo|argumento|forma polar/i,
      definition: 'z = x + iy con i² = −1. Forma polar z = r e^{iθ}: r = |z|, θ = arg(z). Multiplicar en polar = sumar ángulos y multiplicar módulos.',
      keyPoints: ['|z| = √(x² + y²)', 'arg(z) definido modulo 2π', 'e^{iθ} = cos θ + i sin θ (Euler)'],
      formulas: ['z = r e^{iθ}', '|z₁ z₂| = |z₁||z₂|'],
      simGuide: 'Mueve z en el plano: observa r y θ. Multiplicar por e^{iα} rota el vector z un ángulo α.',
      example: { problem: '<p>|3 + 4i| y arg.</p>', solution: '<p>|z| = 5, arg ≈ <strong>53.13°</strong>.</p>' },
    },
    {
      test: /función compleja|analítica|holomorfa|cauchy-riemann/i,
      definition: 'f(z) analítica si derivable en sentido complejo. Cauchy-Riemann: ∂u/∂x = ∂v/∂y, ∂u/∂y = −∂v/∂x con f = u + iv. Holomorfa ⟹ infinitamente diferenciable.',
      keyPoints: ['CR necesarias para analiticidad', 'Grid conforme: preserva ángulos localmente', 'Singularidades donde no es holomorfa'],
      formulas: ['∂u/∂x = ∂v/∂y', '∂u/∂y = −∂v/∂x'],
      simGuide: 'Modo C-R: la malla se deforma conformemente donde f es analítica (sin rotación de ángulos rectos).',
      example: { problem: '<p>f(z) = z². ¿Analítica?</p>', solution: '<p>Sí en <strong>todo ℂ</strong>.</p>' },
    },
    {
      test: /singularidad|residuo|laurent|taylor|integral.*compleja|cauchy/i,
      definition: 'Singularidades: polos, esenciales o removibles. Residuo en polo simple: Res = lim_{z→z₀}(z−z₀)f(z). Teorema del residuo: ∮ f dz = 2πi Σ Res.',
      keyPoints: ['Polo orden n: Laurent con términos (z−z₀)^{−n}', 'Residuo calcula integrales reales difíciles', 'Cauchy-Goursat: integral cero en dominio simplemente conexo'],
      formulas: ['∮ f(z)dz = 2πi Σ Res', 'Res_{z₀} f = 1/(2πi) ∮ f dz'],
      simGuide: 'Contorno alrededor del polo: la integral de línea es 2πi × residuo. Ajusta el contorno y observa el flujo.',
      example: { problem: '<p>∮ 1/z dz sobre |z|=1.</p>', solution: '<p>Res = 1 → integral = <strong>2πi</strong>.</p>' },
    },
    {
      test: /ecuación diferencial|wronskiano|frobenius|sturm|fourier|green/i,
      definition: 'EDO lineales de 2° orden: y″ + p y′ + q y = 0. Wronskiano W(y₁,y₂) ≠ 0 ⟹ soluciones independientes. Sturm-Liouville: autofunciones ortogonales. Green: respuesta a impulso.',
      keyPoints: ['Solución general = c₁ y₁ + c₂ y₂', 'Frobenius: series en singularidades regulares', 'Fourier: expansión en modos seno/coseno'],
      formulas: ['W = y₁ y₂′ − y₂ y₁′', 'y″ + ω² y = 0 → cos ωt, sin ωt'],
      simGuide: 'Ajusta ω y β en la EDO: sub/sobre amortiguamiento cambia la forma de y(t). Wronskiano ≠ 0 confirma independencia.',
      example: { problem: '<p>y″ + 4y = 0, y(0)=1, y′(0)=0.</p>', solution: '<p>y = <strong>cos(2t)</strong>.</p>' },
    },
    {
      test: /gamma|bessel|legendre|hermite|laguerre|armónicos esféricos/i,
      definition: 'Funciones especiales surgen al separar variables: Bessel en cilindros, Legendre/Harmónicos esféricos en esferas, Hermite en oscilador cuántico, Laguerre en átomo de H, Γ generaliza factorial.',
      keyPoints: ['Γ(n+1) = n!', 'J_ν(x) solución de ecuación de Bessel', 'P_l(cos θ) polinomios de Legendre'],
      formulas: ['J₀(x) = Σ (−1)^k (x/2)^{2k}/(k!)²', 'Γ(z) = ∫₀^∞ t^{z−1} e^{−t} dt'],
      simGuide: 'Grafica la función especial: nodos, decaimiento, ortogonalidad según el tipo elegido en variantes.',
      example: { problem: '<p>Γ(5) = ?</p>', solution: '<p>Γ(5) = 4! = <strong>24</strong>.</p>' },
    },
    {
      test: /termodinám|equilibrio|extensivas|intensivas|temperatura|calor|trabajo|entropía|carnot|helmholtz|gibbs|clapeyron|onsager|landau|le chatelier/i,
      definition: 'La termodinámica describe equilibrio y procesos con calor Q, trabajo W y funciones de estado (U, S, H, F, G). Primera ley: ΔU = Q − W. Segunda: dS ≥ δQ/T.',
      keyPoints: ['Extensivas ∝ tamaño (V, n); intensivas no (T, P)', 'Proceso reversible: quasiestático + sin disipación', 'Potenciales F, G útiles según variables fijas'],
      formulas: ['ΔU = Q − W', 'dS ≥ δQ/T', 'PV = nRT', 'η_Carnot = 1 − T_c/T_h'],
      simGuide: 'Diagrama P-V: isoterma, isócora o ciclo de Carnot. Punto recorre el proceso; observa T, P, W.',
      example: { problem: '<p>Gas ideal isotermo: ¿ΔU?</p>', solution: '<p>ΔU = <strong>0</strong> (U solo depende de T).</p>' },
    },
    {
      test: /gradiente|divergencia|rotacional|stokes|gauss|laplaciano|tensor cartesiano/i,
      definition: 'Operadores vectoriales: ∇f (gradiente), ∇·F (divergencia = flujo neto saliente), ∇×F (rotacional = circulación local). Teoremas: Gauss (∮ E·dA = Q/ε₀), Stokes (∮ F·dr = ∬ (∇×F)·dA).',
      keyPoints: ['∇×∇f = 0', '∇·(∇×F) = 0', 'Laplaciano ∇²f = ∇·∇f'],
      formulas: ['∇·E = ρ/ε₀', '∇×E = −∂B/∂t', '∮ F·dr = ∬ (∇×F)·dA'],
      simGuide: 'Campo gradiente: flechas apuntan hacia mayor f. Divergente: fuente/sumidero. Rotacional: remolino.',
      example: { problem: '<p>F = (0,0,z). ¿∇·F?</p>', solution: '<p>∂F_z/∂z = <strong>1</strong>.</p>' },
    },
    {
      test: /coulomb|gauss|poisson|laplace|potencial|multipolo|dieléctric|conductor|capacitor/i,
      definition: 'Electrostática: cargas en reposo. Coulomb F = k q₁q₂/r². Gauss: flujo ∮ E·dA = Q_enc/ε₀. Poisson ∇²V = −ρ/ε₀; Laplace ρ=0. Dipolo y multipolos para distribuciones lejanas.',
      keyPoints: ['E = −∇V', 'Interior conductor E=0 en equilibrio', 'Dieléctrico: D = εE, P = χE'],
      formulas: ['F = k q₁q₂/r²', '∮ E·dA = Q/ε₀', '∇²V = −ρ/ε₀'],
      simGuide: 'Ajusta cargas q₁, q₂: líneas de campo E salen de + y entran en −. Equipotenciales ⊥ a E.',
      example: { problem: '<p>Esfera conductora cargada Q. ¿E en interior?</p>', solution: '<p><strong>E = 0</strong> (equilibrio electrostático).</p>' },
    },
    {
      test: /biot-savart|ampère|magnetost|dipolo magnét|ferro|paramagn|diamagn/i,
      definition: 'Magnetostática: corrientes estacionarias. Biot-Savart dB = (μ₀/4π) I dl×r̂/r². Ampère ∮ B·dl = μ₀ I_enc. Materiales: χ_m pequeño (dia/paramagn) o grande (ferro, histéresis).',
      keyPoints: ['B sin divergencia: ∇·B = 0', 'Solenoide: B ≈ μ₀ n I interior', 'Dipolo m en B: τ = m × B'],
      formulas: ['∮ B·dl = μ₀ I_enc', 'F = I L × B', 'τ = m × B'],
      simGuide: 'Alambre con corriente I: círculos de B alrededor (regla de la mano derecha). Ajusta I y observa |B|.',
      example: { problem: '<p>Alambre I = 10 A, r = 2 cm. ¿B?</p>', solution: '<p>B = μ₀I/(2πr) ≈ <strong>10⁻⁴ T</strong>.</p>' },
    },
    {
      test: /faraday|fem|inducción|maxwell|continuidad|onda.*electro/i,
      definition: 'Faraday: fem = −dΦ_B/dt. Maxwell completa: ∇×E = −∂B/∂t, ∇×B = μ₀J + μ₀ε₀∂E/∂t. Ondas EM en vacío con c = 1/√(μ₀ε₀). Continuidad: ∇·J + ∂ρ/∂t = 0.',
      keyPoints: ['Variación de flujo induce E', 'Corriente de desplazamiento en capacitor', 'E y B perpendiculares en onda plana'],
      formulas: ['∇×E = −∂B/∂t', 'c = 1/√(μ₀ε₀)', '∇·J = −∂ρ/∂t'],
      simGuide: 'Ondas E (azul) y B (naranja) perpendiculares propagándose. Reproduce y observa λ y ω.',
      example: { problem: '<p>Φ crece 0.1 Wb/s. ¿|fem|?</p>', solution: '<p>|fem| = <strong>0.1 V</strong> (magnitud).</p>' },
    },
  ];

  function defaultContent(title, unitTitle, simType, variantLabel) {
    return {
      definition: `«${title}» pertenece a la unidad «${unitTitle}». Es un concepto del programa propedéutico que conecta la formulación matemática con fenómenos físicos medibles.`,
      keyPoints: [
        'Identifica las magnitudes y unidades del enunciado',
        'Relaciona este tema con los anteriores de la misma unidad',
        'Verifica condiciones de validez del modelo',
      ],
      formulas: [],
      simGuide: `La simulación (${variantLabel}) ilustra visualmente aspectos de «${title}». Ajusta parámetros y reproduce para ver la evolución temporal o geométrica.`,
      example: {
        problem: `<p>Problema tipo sobre «${title}»: identifica datos, escribe la ley principal del tema y despeja la incógnita.</p>`,
        solution: '<p>Aplica la definición del tema paso a paso. Verifica unidades y sentido físico del resultado.</p>',
      },
    };
  }

  function getTopicContent(title, unitTitle, simType, variantId, variantLabel) {
    for (const rule of RULES) {
      if (rule.test.test(title)) {
        return {
          definition: rule.definition,
          keyPoints: rule.keyPoints,
          formulas: rule.formulas,
          simGuide: rule.simGuide.replace(/\$\{variantLabel\}/g, variantLabel),
          example: rule.example,
        };
      }
    }
    return defaultContent(title, unitTitle, simType, variantLabel);
  }

  window.getTopicContent = getTopicContent;
})();
